//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUFT_PRUEBA_001
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGROVERSA_PRODUCTIVAEntities : DbContext
    {
        public AGROVERSA_PRODUCTIVAEntities()
            : base("name=AGROVERSA_PRODUCTIVAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_PUFT_DIRECCIONES_SAP> VW_PUFT_DIRECCIONES_SAP { get; set; }
        public virtual DbSet<VW_PUFT_VALI_INSER_DIREC> VW_PUFT_VALI_INSER_DIREC { get; set; }
    }
}
