//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUFT_PRUEBA_001
{
    using System;
    
    public partial class SP_PUFT_FACTURAS_DIRECCIONES_BY_DATE_Result1
    {
        public Nullable<int> n_factura { get; set; }
        public Nullable<long> ORDEN_VENTA { get; set; }
        public Nullable<long> n_remision { get; set; }
        public Nullable<int> n_agente { get; set; }
        public string ShipToCode { get; set; }
        public string cve_cte { get; set; }
        public string Address { get; set; }
        public Nullable<int> LineNum { get; set; }
    }
}
