//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PUFT_PRUEBA_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PUFT_VALI_INSER_DIREC
    {
        public string CardCode { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string AdresType { get; set; }
        public string U_IDSFDC { get; set; }
        public string Address { get; set; }
        public Nullable<int> MyLineNum { get; set; }
        public string cve_cte { get; set; }
        public string UID_SFDC { get; set; }
        public int APLI_INSERT { get; set; }
    }
}
